/// <reference types="node" />
/**
 * Helpers for the spoken-word fixtures in tests/fixtures/silence/ (generated by
 * scripts/generate-silence-fixtures.mjs). Everything here is offline and
 * deterministic: no API key, no network, no ffmpeg.
 */
import { readFileSync } from 'node:fs';
import { SILENCE_MIN_SECONDS, SILENCE_NOISE_DB } from '../config';
import type { PlannedChunk } from '../media/audioChunker';
import type { TranscriptionProvider } from '../transcription/TranscriptionProvider';
import type { AudioSource, SilenceInterval } from '../types/media';
import type { TranscriptResult } from '../types/transcription';

const FIXTURE_DIR = new URL('../../tests/fixtures/silence/', import.meta.url);

export interface FixtureWord {
  word: string;
  start: number;
  end: number;
}

export interface Fixture {
  name: string;
  sampleRate: number;
  samples: Float32Array;
  duration: number;
  /** Word positions known from how the audio was built (never from transcription). */
  words: FixtureWord[];
  /** Pauses inserted between phrases. */
  pauses: SilenceInterval[];
  /** Hand-written ground truth from <name>.txt. */
  expected: string;
}

export function loadFixture(name: string): Fixture {
  const wav = decodeWav(readFileSync(new URL(`${name}.wav`, FIXTURE_DIR)));
  const manifest = JSON.parse(readFileSync(new URL(`${name}.json`, FIXTURE_DIR), 'utf8')) as {
    duration: number;
    words: FixtureWord[];
    pauses: SilenceInterval[];
  };
  return {
    name,
    ...wav,
    duration: wav.samples.length / wav.sampleRate,
    words: manifest.words,
    pauses: manifest.pauses,
    expected: readFileSync(new URL(`${name}.txt`, FIXTURE_DIR), 'utf8'),
  };
}

function decodeWav(buf: Buffer): { sampleRate: number; samples: Float32Array } {
  let offset = 12;
  let sampleRate = 0;
  while (offset + 8 <= buf.length) {
    const id = buf.toString('ascii', offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    const body = offset + 8;
    if (id === 'fmt ') {
      if (buf.readUInt16LE(body + 2) !== 1 || buf.readUInt16LE(body + 14) !== 16) throw new Error('expected mono 16-bit PCM');
      sampleRate = buf.readUInt32LE(body + 4);
    } else if (id === 'data') {
      const samples = new Float32Array(size / 2);
      for (let i = 0; i < samples.length; i++) samples[i] = buf.readInt16LE(body + i * 2) / 32768;
      return { sampleRate, samples };
    }
    offset = body + size + (size % 2);
  }
  throw new Error('no data chunk');
}

/**
 * Same rule as ffmpeg's `silencedetect=noise=…dB:d=…` (what FfmpegAudioSource
 * runs in the browser): a silence is a run of samples whose magnitude stays
 * below the noise floor for at least `minSeconds`. Only [start, end) is
 * analysed, just as the app only decodes the search window; a silence still
 * running at `end` is closed there.
 */
export function detectSilences(
  fixture: Pick<Fixture, 'samples' | 'sampleRate'>,
  start: number,
  end: number,
  noiseDb = SILENCE_NOISE_DB,
  minSeconds = SILENCE_MIN_SECONDS,
): SilenceInterval[] {
  const { samples, sampleRate } = fixture;
  const threshold = 10 ** (noiseDb / 20);
  const first = Math.max(0, Math.round(start * sampleRate));
  const last = Math.min(samples.length, Math.round(end * sampleRate));
  const minRun = Math.round(minSeconds * sampleRate);
  const result: SilenceInterval[] = [];
  let runStart = -1;
  const close = (at: number) => {
    if (runStart >= 0 && at - runStart >= minRun) result.push({ start: runStart / sampleRate, end: at / sampleRate });
    runStart = -1;
  };
  for (let i = first; i < last; i++) {
    if (Math.abs(samples[i]) < threshold) {
      if (runStart < 0) runStart = i;
    } else {
      close(i);
    }
  }
  close(last);
  return result;
}

/**
 * An AudioSource over a fixture. `extract` returns the real PCM samples of the
 * requested range; `findSilences` runs the detector above unless a
 * (deliberately wrong) detector is supplied.
 */
export class FixtureAudioSource implements AudioSource {
  readonly extracted: Array<[number, number]> = [];
  private readonly ranges = new WeakMap<Blob, { start: number; end: number }>();
  private readonly fixture: Fixture;
  private readonly detector: (start: number, end: number) => SilenceInterval[];

  constructor(fixture: Fixture, detector?: (start: number, end: number) => SilenceInterval[]) {
    this.fixture = fixture;
    this.detector = detector ?? ((s, e) => detectSilences(fixture, s, e));
  }

  async probe() {
    return { duration: this.fixture.duration, hasAudio: true };
  }

  async findSilences(start: number, end: number) {
    return this.detector(start, end);
  }

  async extract(start: number, end: number): Promise<Blob> {
    this.extracted.push([start, end]);
    const { samples, sampleRate } = this.fixture;
    const slice = samples.slice(Math.round(start * sampleRate), Math.round(end * sampleRate));
    const blob = new Blob([slice.buffer], { type: 'audio/pcm' });
    this.ranges.set(blob, { start, end });
    return blob;
  }

  rangeOf(blob: Blob): { start: number; end: number } {
    const range = this.ranges.get(blob);
    if (!range) throw new Error('blob was not produced by this source');
    return range;
  }

  async dispose() {}
}

/**
 * Deterministic stand-in for a speech recogniser, so the whole chunk → transcribe
 * → assemble path can run without an API. It is deliberately pessimistic about
 * cut words, which is the failure being tested:
 *
 * - a word whose audio lies entirely inside the chunk is recognised;
 * - a word cut by the chunk edge comes out as a garbled fragment (the letters
 *   proportional to the part that is present), like a real model mishearing
 *   half a word; a sliver under 20 % produces nothing.
 *
 * Word labels come from the fixture's build manifest. Before emitting a word,
 * it checks the chunk's actual samples contain audible sound where the word
 * should be, so a wrongly sliced chunk cannot pass.
 */
export class OracleRecognizer implements TranscriptionProvider {
  readonly id = 'oracle';
  private readonly fixture: Fixture;
  private readonly source: FixtureAudioSource;

  constructor(fixture: Fixture, source: FixtureAudioSource) {
    this.fixture = fixture;
    this.source = source;
  }

  async transcribe(audio: Blob): Promise<TranscriptResult> {
    const { start, end } = this.source.rangeOf(audio);
    const samples = new Float32Array(await audio.arrayBuffer());
    const rate = this.fixture.sampleRate;
    const out: string[] = [];
    for (const w of this.fixture.words) {
      const from = Math.max(w.start, start);
      const to = Math.min(w.end, end);
      if (to <= from) continue;
      const fraction = (to - from) / (w.end - w.start);
      if (fraction < 0.2) continue;
      const peak = peakBetween(samples, Math.round((from - start) * rate), Math.round((to - start) * rate));
      if (peak < 0.02) throw new Error(`no audio for "${w.word}" at ${from.toFixed(3)}s in chunk ${start}-${end}`);
      const letters = w.word.toLowerCase();
      if (fraction >= 1 - 1e-9) out.push(letters);
      else {
        const n = Math.max(1, Math.floor(letters.length * fraction));
        out.push(w.start < start ? letters.slice(-n) : letters.slice(0, n));
      }
    }
    if (out.length === 0) return { text: '' };
    // Formatted like model output: capitalised, comma-separated, full stop.
    const text = out.join(', ');
    return { text: text[0].toUpperCase() + text.slice(1) + '.' };
  }
}

function peakBetween(samples: Float32Array, from: number, to: number): number {
  let peak = 0;
  for (let i = Math.max(0, from); i < Math.min(samples.length, to); i++) peak = Math.max(peak, Math.abs(samples[i]));
  return peak;
}

// ---------------------------------------------------------------- comparison

/**
 * Splits text into comparable words. Only whitespace, punctuation and letter
 * case are normalised; the words themselves stay significant.
 */
export function normalizeWords(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, ' ')
    .split(/\s+/)
    .filter(Boolean);
}

export interface WordReport {
  reference: number;
  /** Word error rate: (substitutions + deletions + insertions) / reference words. */
  wer: number;
  deletions: Array<{ index: number; word: string }>;
  substitutions: Array<{ index: number; expected: string; actual: string }>;
  insertions: Array<{ afterIndex: number; word: string }>;
  /** Expected words that do not appear in the aligned transcript (deletions + substitutions). */
  missing: string[];
}

/** Minimum-edit alignment of expected vs actual words (standard WER). */
export function compareTranscripts(expectedText: string, actualText: string): WordReport {
  const ref = normalizeWords(expectedText);
  const hyp = normalizeWords(actualText);
  const d: number[][] = Array.from({ length: ref.length + 1 }, (_, i) =>
    Array.from({ length: hyp.length + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0)),
  );
  for (let i = 1; i <= ref.length; i++) {
    for (let j = 1; j <= hyp.length; j++) {
      d[i][j] = Math.min(d[i - 1][j - 1] + (ref[i - 1] === hyp[j - 1] ? 0 : 1), d[i - 1][j] + 1, d[i][j - 1] + 1);
    }
  }
  const report: WordReport = { reference: ref.length, wer: 0, deletions: [], substitutions: [], insertions: [], missing: [] };
  let i = ref.length;
  let j = hyp.length;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && d[i][j] === d[i - 1][j - 1] + (ref[i - 1] === hyp[j - 1] ? 0 : 1)) {
      if (ref[i - 1] !== hyp[j - 1]) report.substitutions.unshift({ index: i - 1, expected: ref[i - 1], actual: hyp[j - 1] });
      i--;
      j--;
    } else if (i > 0 && d[i][j] === d[i - 1][j] + 1) {
      report.deletions.unshift({ index: i - 1, word: ref[i - 1] });
      i--;
    } else {
      report.insertions.unshift({ afterIndex: i - 1, word: hyp[j - 1] });
      j--;
    }
  }
  const errors = report.deletions.length + report.substitutions.length + report.insertions.length;
  report.wer = ref.length ? errors / ref.length : 0;
  report.missing = [...report.deletions.map((x) => x.word), ...report.substitutions.map((x) => x.expected)];
  return report;
}

export function formatReport(label: string, r: WordReport, transcript: string): string {
  const parts = [
    `${label}: WER ${(r.wer * 100).toFixed(1)}%`,
    `deletions ${r.deletions.length}${r.deletions.length ? ` [${r.deletions.map((x) => x.word).join(' ')}]` : ''}`,
    `substitutions ${r.substitutions.length}${r.substitutions.length ? ` [${r.substitutions.map((x) => `${x.expected}→${x.actual}`).join(' ')}]` : ''}`,
    `insertions ${r.insertions.length}${r.insertions.length ? ` [${r.insertions.map((x) => x.word).join(' ')}]` : ''}`,
  ];
  return `${parts.join(', ')}\n    transcript: ${JSON.stringify(transcript.trim())}`;
}

// ------------------------------------------------------------ chunk geometry

/**
 * Checks a chunk plan independently of transcription. Returns human-readable
 * violations (empty when the plan is safe):
 * - the first chunk starts at 0 and the last ends at the source duration;
 * - chunks are in order with no uncovered gap;
 * - adjacent chunks share at least `overlap` seconds;
 * - no chunk is longer than `maxSeconds`;
 * - every speech interval lies entirely inside at least one chunk.
 */
export function chunkPlanViolations(
  plan: readonly PlannedChunk[],
  opts: { duration: number; overlap: number; maxSeconds?: number; speech?: readonly SilenceInterval[] },
): string[] {
  const eps = 1e-9;
  const v: string[] = [];
  if (plan.length === 0) return ['no chunks'];
  if (plan[0].startTime !== 0) v.push(`first chunk starts at ${plan[0].startTime}, not 0`);
  const last = plan[plan.length - 1];
  if (Math.abs(last.endTime - opts.duration) > eps) v.push(`last chunk ends at ${last.endTime}, not ${opts.duration}`);
  plan.forEach((c, i) => {
    if (c.id !== i) v.push(`chunk ${i} has id ${c.id}`);
    if (!(c.endTime > c.startTime)) v.push(`chunk ${i} is empty (${c.startTime}-${c.endTime})`);
    if (opts.maxSeconds !== undefined && c.endTime - c.startTime > opts.maxSeconds + eps) {
      v.push(`chunk ${i} is ${(c.endTime - c.startTime).toFixed(3)} s, over the ${opts.maxSeconds} s maximum`);
    }
    if (i === 0) return;
    const prev = plan[i - 1];
    if (!(c.startTime > prev.startTime)) v.push(`chunk ${i} does not start after chunk ${i - 1}`);
    if (c.startTime > prev.endTime + eps) v.push(`gap ${prev.endTime}-${c.startTime} between chunks ${i - 1} and ${i}`);
    else if (prev.endTime - c.startTime < opts.overlap - eps) {
      v.push(`chunks ${i - 1} and ${i} overlap by ${(prev.endTime - c.startTime).toFixed(3)} s, need ${opts.overlap} s`);
    }
  });
  for (const s of opts.speech ?? []) {
    if (!plan.some((c) => c.startTime <= s.start + eps && c.endTime >= s.end - eps)) {
      v.push(`speech ${s.start.toFixed(3)}-${s.end.toFixed(3)} is not inside any single chunk`);
    }
  }
  return v;
}
